# Generated by Django 5.2.2 on 2025-06-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('isActive', models.BooleanField(default=True)),
                ('cityIncharge', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleIssue', models.TextField()),
                ('canRunInWard', models.CharField(max_length=255)),
                ('canRunInWardResolved', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('driverId', models.CharField(max_length=255)),
                ('driverName', models.CharField(max_length=255)),
                ('mechanicName', models.CharField(max_length=255)),
                ('jobCardId', models.CharField(blank=True, max_length=255, null=True)),
                ('repairCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolvedDate', models.DateTimeField(blank=True, null=True)),
                ('resolvedDescription', models.TextField(blank=True, null=True)),
                ('rootCauses', models.TextField(blank=True, null=True)),
                ('workingHrs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('isBillAvailable', models.BooleanField(default=False)),
                ('unpaidBills', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('reopen', 'Reopen')], max_length=50)),
                ('reopenKey', models.CharField(blank=True, max_length=255, null=True)),
                ('updateKey', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmBy', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmDate', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('createdTime', models.TimeField(blank=True, null=True)),
                ('creationDate', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('isReturnRequiredValue', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=255)),
                ('currentCity', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_parts', to='vm_city.issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='vm_city.vehicle'),
        ),
        migrations.CreateModel(
            name='CityTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newCity', models.CharField(max_length=255)),
                ('_at', models.DateTimeField(auto_now_add=True)),
                ('_by', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='vm_city.vehicle')),
            ],
        ),
    ]
