# Generated by Django 5.2.2 on 2025-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0002_issue_firebase_id_alter_issue_canruninward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='vehicle',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
