# Generated by Django 5.2.2 on 2025-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0005_alter_issue_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
