# Generated by Django 5.2.2 on 2025-06-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0006_alter_issue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('CreatedById', models.CharField(max_length=25)),
            ],
        ),
    ]
