# Generated by Django 5.2.2 on 2025-06-17 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0007_rootcause'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepart',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vm_city.parts'),
        ),
        migrations.AddField(
            model_name='issuepart',
            name='stock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuepart',
            name='issue',
            field=models.ForeignKey(blank=True, db_column='firebase_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_parts', to='vm_city.issue', to_field='firebase_id'),
        ),
    ]
