# Generated by Django 5.2.2 on 2025-06-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0008_issuepart_part_issuepart_stock_alter_issuepart_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepart',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
