# Generated by Django 5.2.2 on 2025-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0009_issuepart_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepart',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
