# Generated by Django 5.2.2 on 2025-06-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0010_alter_issuepart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='firebase_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='isReturnRequiredValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
