# Generated by Django 5.2.2 on 2025-06-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0011_parts_firebase_id_alter_parts_code_alter_parts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
