# Generated by Django 5.2.2 on 2025-06-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0012_alter_issuepart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created_date',
        ),
    ]
