# Generated by Django 5.2.2 on 2025-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0013_remove_vendor_created_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
