# Generated by Django 5.2.6 on 2025-09-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0014_vendor_firebase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytransferhistory',
            name='_at',
            field=models.DateTimeField(),
        ),
    ]
