# Generated by Django 5.2.6 on 2025-09-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_city', '0015_alter_citytransferhistory__at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='firebase_id',
            new_name='part_id',
        ),
    ]
